tags:
    -   "Usuario"
summary: "Cambia el password del Usuario logueado"
description: "Cambia el password de un Usuario existente indicando el password anterior y el nuevo password. El usuario debe estar logueado, de lo contrario se rechaza la operacion"
operationId: "postCambiarPassword"
parameters:
    -   in: body
        name: body
        schema:
            properties:
                password:
                    type: string
                    example: '123456'
                nuevoPassword:
                    type: string
                    example: '654321'
security:
  - Bearer: []
responses:
    200:
        description: Password cambiado exitosamente
        schema:
            $ref: '#/definitions/Usuario'