"""tabla productos actualizada campo imagen a tipo array

Revision ID: 13fc40f61101
Revises: f0c1037e2b6a
Create Date: 2023-09-05 16:34:00.814009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fc40f61101'
down_revision = 'f0c1037e2b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagenes', sa.ARRAY(sa.Text()), nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('imagenes')

    # ### end Alembic commands ###
