"""cambio tabla usuarios, se agrego 2 columna nombre y apellido , tipousuario valor por defecto CLIENTE

Revision ID: 2008a35b9cfe
Revises: 13fc40f61101
Create Date: 2023-09-05 16:54:00.842851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2008a35b9cfe'
down_revision = '13fc40f61101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
