"""correcion tabla detalle pedidos

Revision ID: ba8a5f6fddb3
Revises: 356f3e7c4389
Create Date: 2023-09-13 18:48:50.672872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8a5f6fddb3'
down_revision = '356f3e7c4389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_total', sa.Float(), nullable=False))
        batch_op.drop_column('subTotal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subTotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('sub_total')

    # ### end Alembic commands ###
